version: "3"
services:
  api_gateway:
    build: .
    ports:
    - "8080:8080"
    environment:
      RECIPES_URL: 192.168.99.100
      RECIPES_PORT: 8081
      COLLECTIONS_URL: 192.168.99.100
      COLLECTIONS_PORT: 8082
      USERS_URL: 192.168.99.100
      USERS_PORT: 8083
      NOTIFICATIONS_URL: 192.168.99.100
      NOTIFICATIONS_PORT: 8084
      COMMENTS_URL: 192.168.99.100
      COMMENTS_PORT: 8085
